// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'abc',
    appId: '123',
    messagingSenderId: 'asd',
    projectId: '123',
    authDomain: 'abc',
    storageBucket: 'abac',
    measurementId: 'G-aca',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'abc',
    appId: '123',
    messagingSenderId: 'asd',
    projectId: 'asd',
    storageBucket: 'asd',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'abc',
    appId: '123',
    messagingSenderId: 'asd',
    projectId: 'asd',
    storageBucket: 'asd',
    iosBundleId: 'asd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'abc',
    appId: '123',
    messagingSenderId: 'asd',
    projectId: 'asd',
    storageBucket: 'asd',
    iosBundleId: 'casdt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'abc',
    appId: '123',
    messagingSenderId: 'asd',
    projectId: 'asd-asd-asd',
    authDomain: 'asd-chat-asd.asd.com',
    storageBucket: 'asd-asd-asd.appspot.com',
    measurementId: 'G-asd',
  );
}
