// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2fyqPW7H0fOovyuD1KUSMIQpH7neOaDA',
    appId: '1:316442417259:web:cd8fd4242a2a04e7d7b92e',
    messagingSenderId: '316442417259',
    projectId: 'flash-chat-1a6e9',
    authDomain: 'flash-chat-1a6e9.firebaseapp.com',
    storageBucket: 'flash-chat-1a6e9.appspot.com',
    measurementId: 'G-Y5WP2WQ49M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDff5BxWFDsEZOFiBs23qDSveM9a3P5dEk',
    appId: '1:316442417259:android:b9df1f7c11f436c4d7b92e',
    messagingSenderId: '316442417259',
    projectId: 'flash-chat-1a6e9',
    storageBucket: 'flash-chat-1a6e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQqD5wE8l3QtoKTCWOp9ao6GN9aiXKWsE',
    appId: '1:316442417259:ios:a6448cafaf15fa55d7b92e',
    messagingSenderId: '316442417259',
    projectId: 'flash-chat-1a6e9',
    storageBucket: 'flash-chat-1a6e9.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQqD5wE8l3QtoKTCWOp9ao6GN9aiXKWsE',
    appId: '1:316442417259:ios:a6448cafaf15fa55d7b92e',
    messagingSenderId: '316442417259',
    projectId: 'flash-chat-1a6e9',
    storageBucket: 'flash-chat-1a6e9.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2fyqPW7H0fOovyuD1KUSMIQpH7neOaDA',
    appId: '1:316442417259:web:5cd3c5ecd68f6fbed7b92e',
    messagingSenderId: '316442417259',
    projectId: 'flash-chat-1a6e9',
    authDomain: 'flash-chat-1a6e9.firebaseapp.com',
    storageBucket: 'flash-chat-1a6e9.appspot.com',
    measurementId: 'G-138RYGVWS5',
  );
}
